apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth-dev

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- service.yaml
- deployment.yaml

images:
- name: ghcr.io/donghyeonka/project-auth-server
  newName: ghcr.io/donghyeonka/project-auth-server
  newTag: f4e5f91
