// 1. 플러그인 관리 (Spring Boot 등 플러그인 버전을 여기서 중앙 통제)
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

// 2. 의존성 관리 (버전 카탈로그)
dependencyResolutionManagement {
    // 하위 모듈들이 독단적으로 다른 저장소(repository)를 쓰는 것을 금지!
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
    
    // '버전 카탈로그' 세팅 (라이브러리 메뉴판)
    versionCatalogs {
        create("libs") {
            // [버전 정의]
            version("springBoot", "4.0.3")
            version("springDependencyManagement", "1.1.7")
            version("lombok", "1.18.30")
            version("springdoc", "3.0.2")

            // [플러그인 정의]
            plugin("spring-boot", "org.springframework.boot").versionRef("springBoot")
            plugin("spring-dependency-management", "io.spring.dependency-management").versionRef("springDependencyManagement")

            // [라이브러리 정의]
            library("lombok", "org.projectlombok", "lombok").versionRef("lombok")
            library("springdoc-openapi-webmvc-ui", "org.springdoc", "springdoc-openapi-starter-webmvc-ui").versionRef("springdoc")
        }
    }
}

rootProject.name = 'project-auth-server'

include("bootstrap")
include("domain")
include("application")
include("presentation")
include("infrastructure")
include("common")
