apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  POSTGRES_SUPERUSER: postgres
  POSTGRES_DEFAULT_DB: postgres
  AUTH_DB_NAME: project_auth
  AUTH_DB_USER: project_auth
  KEYCLOAK_DB_NAME: keycloak
  KEYCLOAK_DB_USER: keycloak
  KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME: admin
  KEYCLOAK_CLIENT_ID: project-auth-server
  AUTH_SERVER_BASE_URL: http://auth-server.auth-dev.svc.cluster.local:8080
  VAULT_TRANSIT_KEY_NAME: project-auth-jwt
