apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - keycloak-service.yaml
  - keycloak-deployment.yaml
  - keycloak-client-sync-job.yaml
  - vault-service.yaml
  - vault-deployment.yaml
  - vault-init-job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: postgres-init-script
    files:
      - files/postgres/01-init-project-auth-databases.sh
  - name: keycloak-realm-import
    files:
      - files/keycloak/project-auth-realm.json
  - name: vault-init-script
    files:
      - files/vault/01-init-transit.sh
