apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: vault-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: vault-init
          image: hashicorp/vault:1.18
          command:
            - /bin/sh
            - /vault-init/01-init-transit.sh
          env:
            - name: VAULT_ADDR
              value: http://vault.platform.svc.cluster.local:8200
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: platform-secret
                  key: VAULT_DEV_ROOT_TOKEN_ID
            - name: VAULT_TRANSIT_KEY_NAME
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: VAULT_TRANSIT_KEY_NAME
          volumeMounts:
            - name: vault-init-script
              mountPath: /vault-init/01-init-transit.sh
              subPath: 01-init-transit.sh
      volumes:
        - name: vault-init-script
          configMap:
            name: vault-init-script
            defaultMode: 0555
