apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: auth-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  description: Project Auth Server dev deployment project
  
  sourceRepos:
    - https://github.com/DongHyeonka/Project-Auth-Server.git
  
  destinations:
    - namespace: auth-dev
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: StatefulSet
    - group: "apps"
      kind: ReplicaSet
    - group: "autoscaling"
      kind: HorizontalPodAutoscaler
    - group: "batch"
      kind: Job
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "policy"
      kind: PodDisruptionBudget
  
  orphanedResources:
    warn: true
